const actions = {
    GET_CURRENT_WEATHER_DATA: 'GET_CURRENT_WEATHER_DATA',
    GET_WEEKLY_WEATHER_DATA: 'GET_WEEKLY_WEATHER_DATA',
    SET_LOADING_STATE: 'SET_LOADING_STATE'
};

export default actions;